name: "Run terraform plan"
description: "Run terraform plan on AWS"

inputs:
  iam_role:
    description: "AWS IAM role"
    required: true
  aws_region:
    description: "AWS region"
    required: true
  dir:
    description: "terraform directory"
    required: true
  aws_environment:
    description: "AWS Environment"
    required: true

runs:
  using: "composite"
  steps:
      - name: Login
        id: login
        # from https://github.com/aws-actions/configure-aws-credentials/tree/main
        uses: aws-actions/configure-aws-credentials@8337ca3433e1716b025580b435b374762892752f
        with:
          role-to-assume: ${{ inputs.iam_role }}
          aws-region: ${{ inputs.aws_region }}

      - name: Cache terraform modules
        id: cache-terraform-modules
        uses: actions/cache@6fd2d4538ca777f67fccddb233cf1a8ff1339012
        with:
          path: ${{ inputs.dir }}/.terraform
          key: terraform-${{ inputs.dir }}-${{ github.sha }}
          restore-keys: |
            terraform-${{ inputs.dir }}

      - name: Terraform plan
        shell: bash
        run: |
          export PATH="${HOME}/bin:$PATH"

          cd ${{ inputs.dir }}

          bash terraform.sh plan ${{ inputs.aws_environment }} -lock-timeout=300s -lock=false
