name: Static Analysis
description: It performs static analysis on Terraform azure projects

inputs:
  precommit_version:
    required: false
    description: Version of pre-commit-terraform release
    default: 'v1.89.1@sha256:1ea921bc4fe87651d41677218e537afdcdb8202e757e554b9866668eaba144c5'

runs:
  using: "composite"
  steps:
    - name: ⚡ Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive

    - name: 🏁 Init terraform folders
      id: init_terraform_folders
      shell: bash
      run: |
        echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
        echo    "+ 🏁 INIT TERRAFORM FOLDERS 🏁 +"
        echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-\n"

        FOLDERS=$(find . -type f -name '*.tf' -not -path '*/.terraform/*' -exec dirname {} \; | sort -u)
        echo "FOLDERS=${FOLDERS}"

        pids=()

        TAG=$(cat .terraform-version)
        docker pull hashicorp/terraform:$TAG
        root_folder=$(pwd)
        for f in $FOLDERS; do
          pushd "$(pwd)/${f}"
            echo "ℹ️Processing folder: ${f}"
            if [ -f 99_main.tf ]; then
              sed -i -e 's/  backend "azurerm" {}//g' 99_main.tf
            fi
            docker run -v $root_folder:/tmp -w /tmp/${f} hashicorp/terraform:$TAG init &
            pids+=($!)
          popd

        done

        for pid in "${pids[@]}"; do
          wait "$pid"
        done

    - name: Show precommit version
      shell: bash
      run: |
        echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
        echo    "+ 1️⃣  SHOW PRECOMMIT VERSION 1️⃣  +"
        echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\n"

        TAG=${{ inputs.precommit_version }}
        docker run --rm --entrypoint cat ghcr.io/antonbabenko/pre-commit-terraform:$TAG /usr/bin/tools_versions_info

    - name: 🚨 Run precommit
      id: run_precommit
      shell: bash
      run: |
        echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
        echo    "+- 🚨 PRECOMMIT TERRAFORM 🚨 -+"
        echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\n"

        TAG=${{ inputs.precommit_version }}
        docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
