name: "Release action"
description: "Run release action: create tag and release"

inputs:
  github_token:
    description: "Github token used by the action"
    required: true
  semantic_version:
    description: "(Optional) Specify version range for semantic-release."
    required: false
    default: 21.1.1
  ci:
    description: "(Optional) Whether to run semantic release with CI support."
    required: false
    default: "false"
  branches:
    description: "(Optional) The branches on which releases should happen."
    required: false
    default: |
      [
        'master',
        'main'
      ]
  extra_plugins:
    description: "(Optional) Extra plugins for pre-install."
    required: false
    default: |
      @semantic-release/release-notes-generator@13.0.0
      @semantic-release/git@10.0.1

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 #v4.1.0
        with:
          semantic_version: ${{ inputs.semantic_version }}
          ci: ${{ inputs.ci }}
          branches: ${{ inputs.branches }}
          extra_plugins: ${{ inputs.extra_plugins }}
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
