name: "Release action"
description: "Run release action: create tag and release"

outputs:
  new_release_published:
    description: 'Whether a new release was published'
    value: ${{ steps._release.outputs.new_release_published }}
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps._release.outputs.new_release_version }}
  new_release_major_version:
    description: 'Major version of the new release'
    value: ${{ steps._release.outputs.new_release_major_version }}
  new_release_minor_version:
    description: 'Minor version of the new release'
    value: ${{ steps._release.outputs.new_release_minor_version }}
  new_release_patch_version:
    description: 'Patch version of the new release'
    value: ${{ steps._release.outputs.new_release_patch_version }}
  new_release_git_head:
    description: 'The sha of the last commit being part of the new release.'
    value: ${{ steps._release.outputs.new_release_git_head }}
  new_release_git_tag:
    description: 'The Git tag associated with the new release.'
    value: ${{ steps._release.outputs.new_release_git_tag }}
  last_release_version:
    description: 'Version of the previous release, if there was one.'
    value: ${{ steps._release.outputs.last_release_version }}
  last_release_git_head:
    description: 'The sha of the last commit being part of the last release, if there was one.'
    value: ${{ steps._release.outputs.last_release_git_head }}
  last_release_git_tag:
    description: 'The Git tag associated with the last release, if there was one.'
    value: ${{ steps._release.outputs.last_release_git_tag }}

inputs:
  github_token:
    description: "Github token used by the action"
    required: true
  semantic_version:
    description: "(Optional) Specify version range for semantic-release."
    required: false
    default: 24.1.1
  ci:
    description: "(Optional) Whether to run semantic release with CI support."
    required: false
    default: "false"
  branches:
    description: "(Optional) The branches on which releases should happen."
    required: false
    default: |
      [
        'master',
        'main'
      ]
  extra_plugins:
    description: "(Optional) Extra plugins for pre-install."
    required: false
    default: |
      @semantic-release/release-notes-generator@13.0.0
      @semantic-release/github@v10.3.5
  tag_format:
    description: "Specify format of tag. Default is v${version}"
    default: "v${version}"

runs:
  using: "composite"
  steps:
      - name: Checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        id: _release
        # from https://github.com/cycjimmy/semantic-release-action/releases/tag/v4.1.1
        uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 #v4.1.1
        with:
          semantic_version: ${{ inputs.semantic_version }}
          ci: ${{ inputs.ci }}
          branches: ${{ inputs.branches }}
          extra_plugins: ${{ inputs.extra_plugins }}
          tag_format: ${{ inputs.tag_format }}
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
