name: "Release and docker build & push action"
description: "Release and build/push docker image into github package repository"

inputs:
  github_token:
    description: "Github token used by the action"
    required: true
  docker_context_path:
    description: "Dockerfile context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
      - name: Release and tag action
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/release-action@main #
        with:
          github_token: ${{ inputs.github_token }}

      - name: Log in to the Github Container registry
        id: docker_login
        if: steps.release.outputs.new_release_published == 'true'
        # from https://github.com/docker/login-action/commits/master
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 #v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.github_token }}

      - name: Build and push Docker image with release version
        id: docker_build_push
        if: steps.release.outputs.new_release_published == 'true'
        # from https://github.com/docker/build-push-action/commits/master
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c #v6.3.0
        with:
          context: ${{ inputs.docker_context_path }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:v${{ steps.release.outputs.new_release_version }}
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
