name: "Run terraform plan"
description: "Run terraform plan on Azure"

inputs:
  client_id:
    description: "Azure service principal App Id"
    required: true
  tenant_id:
    description: "Azure tenant id"
    required: true
  subscription_id:
    description: "Azure subscription Id"
    required: true
  dir:
    description: "terraform directory"
    required: true
  azure_environment:
    description: "Azure Environment"
    required: true
  terraform_action:
    description: "Terraform action that must be executed. E.g. plan|apply|init..."
    required: true
  aks_name:
    description: "AKS name"
    required: true


runs:
  using: "composite"
  steps:
      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ inputs.client_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Cache terraform modules
        id: cache-terraform-modules
        uses: actions/cache@6fd2d4538ca777f67fccddb233cf1a8ff1339012
        with:
          path: ${{ inputs.dir }}/.terraform
          key: terraform-${{ inputs.dir }}-${{ github.sha }}
          restore-keys: |
            terraform-${{ inputs.dir }}

      - name: Check kubeconfig
        shell: bash
        run: |
          echo "🔦 Check kubeconfig file exists"

          if [[ ! -f "$HOME/.kube/config-${{ inputs.aks_name }}" ]]; then
            echo "❌ kubeconfig file doesn't exist into localtion: $HOME/.kube/config-${{ inputs.aks_name }}"
            exit 1
          else
            echo "✅ Kubeconfig file is present under: $HOME/.kube/config-${{ inputs.aks_name }}"
          fi

      - name: Terraform ${{ inputs.terraform_action }}
        shell: bash
        run: |
          export PATH="${HOME}/bin:$PATH"
          export ARM_CLIENT_ID=${{ inputs.client_id }}
          export ARM_TENANT_ID=${{ inputs.tenant_id }}
          export ARM_SUBSCRIPTION_ID=${{ inputs.subscription_id }}
          export ARM_USE_OIDC=true
          export ARM_USE_AZUREAD=true
          export ARM_STORAGE_USE_AZUREAD=true

          cd "${{ inputs.dir }}" || exit

          echo "[INFO] 🚀 Run terraform ${{ inputs.terraform_action }} + kubernetes"
          if [[ "${{ inputs.terraform_action }}" == "apply" ]]; then
            bash terraform.sh ${{ inputs.terraform_action }} ${{ inputs.azure_environment }} -auto-approve -lock-timeout=300s -lock=false
          else
            bash terraform.sh ${{ inputs.terraform_action }} ${{ inputs.azure_environment }} -lock-timeout=300s -lock=false
          fi
