name: "Configure kubectl context on an EKS cluster"
description: "Configure kubectl context on an EKS cluster"

inputs:
  aws_iam_role:
    description: "AWS IAM role"
    required: true
  aws_region:
    description: "AWS region"
    required: true
  eks_cluster_name:
    description: "Name of the EKS cluster"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login
      id: login
      # from https://github.com/aws-actions/configure-aws-credentials/tree/main
      uses: aws-actions/configure-aws-credentials@8337ca3433e1716b025580b435b374762892752f
      with:
        role-to-assume: ${{ inputs.aws_iam_role }}
        aws-region: ${{ inputs.aws_region }}

    - name: AWS Update Kube Config
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.eks_cluster_name }}
