name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release action
        uses: ./global/release-action # same repo
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
